PJW-3479: Updates for compatability with dynamodb
poached/sails-generate-ember-blueprints pull request #7
Opened 2018-11-06 22:24 UTC by jcowley

2018-11-09 05:13 UTC, mossymaker requested changes
Minor issue; could probably get by as-is.

2018-11-09 05:13 UTC, callovarne commented on templates/basic/api/blueprints/create.js
> +      Model.getPrimaryKeys().map(key => {
Since the return value isn't used, would it make more sense to use a _forEach_?

2018-11-12 23:03 UTC, jcowley commented
updated

2018-11-13 20:36 UTC, mossymaker approved these changes

2018-11-13 23:15 UTC, merged